skip-check:
  - CKV_AWS_145  # Ensure that S3 buckets are encrypted with KMS by default
  - CKV2_AWS_62  # Ensure S3 buckets should have event notifications enabled
  - CKV_AWS_18   # Ensure the S3 bucket has access logging enabled
  - CKV_AWS_144  # Ensure that S3 bucket has cross-region replication enabled
